config/routes.rb
Rails.application.routes.draw do
  resources :products do
    member do
      post 'add_to_cart', to: 'carts#add_to_cart'
    end
  end
  get '/users/signin', to: 'users#signin'
  post '/users/signin', to: 'users#create_user_session'
  get '/users/signup', to: 'users#signup'
  post '/users/register', to: 'users#register'
  delete '/users/signout', to: 'users#signout'
  post '/carts/checkout', to: 'carts#checkout'
  get '/carts/view_cart', to: 'carts#view_cart'
  root to: 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image
  has_many :order_items
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  has_many :products

  attr_accessor :password_confirmation

  before_create :update_password
  validates :email, presence: true
  validates :password, presence: true
  validate :confirm_password, if: :new_record?

  enum role: %w[Buyer Admin]

  def valid_password?(password)
    hmac = OpenSSL::HMAC.new('This is my secret', 'sha256')
    hmac << password
    ActiveSupport::SecurityUtils.secure_compare(
      hmac.hexdigest,
      self.password
    )
  end

  private

  def confirm_password
    errors.add(:password, "doesn't match with confirm password") if password_confirmation.present? && password != password_confirmation
  end

  def update_password
    hmac = OpenSSL::HMAC.new('This is my secret', 'sha256')
    hmac << password

    self.password = hmac.hexdigest
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

  def authenticate_user
    unless session[:user_id]
      redirect_to users_signin_path
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user, only: [:checkout]
  before_action :set_or_initialize_cart

  def add_to_cart
    cart_item = @cart.find { |ci| ci['product_id'] == params[:id] }
    if cart_item
      cart_item['quantity'] += 1
      flash[:success] = "Product Updated Successfully"
    else
      @cart.append(product_id: params[:id], quantity: 1)
      flash[:success] = "Product Added Successfully"
    end
    redirect_to request.referer
  end

  def view_cart; end

  def checkout
    order = current_user.orders.new
    @cart.each do |ci|
      order.order_items.new(ci)
    end
    order.save!
    session[:cart] = []
    flash[:success] = "Order Created Successfully"
    redirect_to root_path
  end

  private

  def cart_item_params
    params.permit(:product_id, :quantity)
  end

  def set_or_initialize_cart
    if session[:cart]
      @cart = session[:cart]
    else
      @cart = session[:cart] = []
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(:name, :price, :quantity)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def register
    @user = User.new(signup_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render 'signup'
    end
  end

  def signup
    @user = User.new
  end

  def create_user_session
    @user = User.find_by(email: signin_params[:email])
    if @user && @user.valid_password?(signin_params[:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render 'signin'
    end
  end

  def signin
    @user = User.new
  end

  def signout
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def signup_params
    params.require(:user).permit(:email, :password, :name, :password_confirmation).merge(role:0)
  end

  def signin_params
    params.permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def items_present_in_cart
    session[:cart].present? && session[:cart].any?
  end

  def find_product product_id
    Product.find(product_id)
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/view_cart.html.erb
<%= render 'layouts/navbar' %>
<p id="notice"><%= notice %></p>
<h1>Cart Items</h1>
<table class="table">
  <thead>
  <tr>
    <th>Avatar</th>
    <th>Product</th>
    <th>Quantity</th>
    <th>Unit Price</th>
    <th>Total</th>
  </tr>
  </thead>
  <tbody>
  <% total_amount = 0.0 %>
  <% @cart.each do |item| %>
    <% product = find_product item['product_id'] %>
    <tr>
      <td><%= image_tag(url_for(product.image) ,class: 'table-user-thumb') if product.image.attached? %> </td>
      <td><%= product.name %></td>
      <td><%= item['quantity'] %></td>
      <td><%= product.price %></td>
      <td><%= product.price * item['quantity'].to_f %></td>
      <% total_amount = total_amount + product.price * item['quantity'].to_f %>
    </tr>
  <% end %>
  <tr>
    <td></td>
    <td></td>
    <td><strong>TOTAL:</strong></td>
    <td><%= total_amount %></td>
  </tr>
  </tbody>
</table>
<div style="text-align: center">
  <%= link_to "Place Order", carts_checkout_path, data: { method: :post }, class: 'custom-show-btn btn btn-info' %>
  <%= link_to "Continue Shopping", root_path, class: 'custom-show-btn btn btn-info' %>
</div>

app/views/layouts/_navbar.html.erb
<% unless current_user.present? %>
  <%= link_to "Sign In", users_signin_path, class: 'btn btn-primary custom-button' %>
  <%= link_to "Register", users_signup_path, class: 'btn btn-primary custom-button' %>
<% else %>
  <%= link_to "Logout", users_signout_path, method: :delete,  class: 'btn btn-primary custom-button' %>
<% end %>
<% if items_present_in_cart && @cart.blank? || current_user.present? && current_user.role == 'Buyer'%>
  <%= link_to "Checkout", carts_view_cart_path, class: 'btn btn-primary custom-button' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BasisEcom</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<script>
    $(document).on('turbolinks:load', function () {
        function show_popups(type, messsage) {
            toastr[type](messsage);
        }

        <% flash.each do |f| %>
        <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'success') %>
        show_popups('<%= type %>', '<%= f[1] %>');
        <% end %>
    })

</script>
<body>
<%= yield %>
</body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<%= render 'layouts/navbar' %>
<p id="notice"><%= notice %></p>
<h1>Products</h1>
<table class="table dataTable">
  <thead>
  <tr>
    <th>Avatar</th>
    <th>Name</th>
    <th>Price</th>
    <th>Quantity</th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @products.each do |product| %>
    <tr>
      <td><%= image_tag(url_for(product.image), class: 'table-user-thumb') if product.image.attached? %> </td>
      <td><%= product.name %></td>
      <td><%= product.price %></td>
      <td><%= product.quantity %></td>
      <td><%= link_to 'Show', product %></td>
      <td><%= link_to 'Add to cart', add_to_cart_product_path(product.id), method: :post if current_user&.role == 'Buyer' || !current_user.present? %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>
<% if current_user&.role == 'Admin' %>
  <%= link_to 'New Product', new_product_path %>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<%= render 'layouts/navbar' %>
<div class="container">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">

      <div class="modal-body">
        <div class="form-title text-center">
          <%= image_tag(url_for(@product.image), class: 'show-img') if @product.image.attached? %>
        </div>
        <div class="d-flex flex-column text-center">
          <p>
            <strong>Name:</strong>
            <%= @product.name %>
          </p>

          <p>
            <strong>Price:</strong>
            <%= @product.price %>
          </p>

          <p>
            <strong>Quantity:</strong>
            <%= @product.quantity %>
          </p>
        </div>
      </div>
      <div class="modal-footer d-flex justify-content-center">
        <% if current_user&.role == 'Buyer' || !current_user.present? %>
          <%= link_to 'Add to cart', add_to_cart_product_path(@product.id), method: :post, class: 'text-info' %>
        <% else %>
          <%= link_to 'Edit', edit_product_path(@product) %> |
        <% end %>
        <%= link_to 'Back', products_path %>
      </div>
    </div>
  </div>
</div>

app/views/users/signin.html.erb
<%= form_with(url: users_signin_path, local: true) do |f| %>
  <div class="container">
    <div class="modal-content">
      <div class="modal-body">
        <div class="form-title text-center">
          <h4>Login</h4>
        </div>
        <div class="d-flex flex-column text-center">
            <div class="form-group">
              <%= f.label :email %>
              <%= f.email_field :email, required: true, class: "form-control", placeholder: "Your email address..." %>
            </div>
            <div class="form-group">
              <%= f.label :password %>
              <%= f.password_field :password, required: true, class: "form-control", placeholder: "Your password..." %>
            </div>
            <%= f.submit "Login", class: "btn btn-info btn-block btn-round" %>
        </div>
      </div>
      <div class="modal-footer d-flex justify-content-center">
        <div class="signup-section">Not a member yet? <a href="<%= users_signup_path %>" class="text-info"> Sign Up</a>.</div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/signup.html.erb
<%= form_for(@user, url: users_register_path) do |f| %>

  <div class="container">
    <div class="modal-content">
      <div class="modal-body">
        <div class="form-title text-center">
          <h4>Register</h4>
        </div>
        <% if @user.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="d-flex flex-column text-center">
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, required: true, class: "form-control", placeholder: "Your name..." %>
          </div>
          <div class="form-group">
            <%= f.label :email %>
            <%= f.email_field :email, required: true, class: "form-control", placeholder: "Your email address..." %>
          </div>
          <div class="form-group">
            <%= f.label :password %>
            <%= f.password_field :password, required: true, class: "form-control", placeholder: "Your password..." %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, required: true, class: "form-control", placeholder: "Your confirm password..." %>
          </div>
          <%= f.submit "Register", class: "btn btn-info btn-block btn-round" %>
        </div>
      </div>
      <div class="modal-footer d-flex justify-content-center">
        <div class="signup-section">Already a member? <a href="<%= users_signin_path %>" class="text-info"> Sign In</a>.
        </div>
      </div>
    </div>
  </div>
<% end %>